workflows:
  version: 2
  build-deploy:
    jobs:
      - build

version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.8-jessie-node
    steps:
      - checkout
      - restore_cache:
          key: deps-py-{{ .Branch }}-{{ checksum "requirements/development.txt" }}
      - run:
          # https://discuss.circleci.com/t/circleci-python-docker-images-disallow-pip-install-due-to-directory-ownership/12504
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/development.txt
      - save_cache:
          key: deps-py-{{ .Branch }}-{{ checksum "requirements/development.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            flake8
            coverage run -m nose
            coveralls
